// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using store.Models;
using System;

namespace store.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20171011021534_add desc")]
    partial class adddesc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("store.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName");

                    b.Property<int>("ProductId");

                    b.Property<int?>("ProductModelId");

                    b.HasKey("Id");

                    b.HasIndex("ProductModelId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("store.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("ImageData");

                    b.Property<int>("ProductId");

                    b.Property<int?>("ProductModelId");

                    b.HasKey("Id");

                    b.HasIndex("ProductModelId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("store.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("ProductModel");
                });

            modelBuilder.Entity("store.Models.Category", b =>
                {
                    b.HasOne("store.Models.ProductModel")
                        .WithMany("Cetegories")
                        .HasForeignKey("ProductModelId");
                });

            modelBuilder.Entity("store.Models.Image", b =>
                {
                    b.HasOne("store.Models.ProductModel")
                        .WithMany("Images")
                        .HasForeignKey("ProductModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
